version: '3.9'

services:

  docker-db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    container_name: docker_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=root

  car-hire.api:
    build:
      context: .
      dockerfile: src/Car-hire.API/Dockerfile
    container_name: api
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - docker-db
        
volumes:
  pgdata: