// <auto-generated />
using System;
using Car_hire.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Car_hire.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240307212608_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "brand", new[] { "bmw", "mercedes", "toyota", "volvo", "audi" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status", new[] { "busy", "repair", "available" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("HirePrice")
                        .HasColumnType("double precision");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "Audi",
                            HirePrice = 307.0,
                            Mileage = 95816,
                            Number = "7158 IK-6",
                            SeatingCapacity = 4,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Audi",
                            HirePrice = 162.0,
                            Mileage = 8974,
                            Number = "3960 SG-2",
                            SeatingCapacity = 4,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "Audi",
                            HirePrice = 885.0,
                            Mileage = 39424,
                            Number = "8925 HP-5",
                            SeatingCapacity = 8,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 4,
                            Brand = "Mercedes",
                            HirePrice = 509.0,
                            Mileage = 47012,
                            Number = "6531 QD-2",
                            SeatingCapacity = 5,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 5,
                            Brand = "Mercedes",
                            HirePrice = 392.0,
                            Mileage = 44109,
                            Number = "9222 TB-1",
                            SeatingCapacity = 4,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 6,
                            Brand = "Mercedes",
                            HirePrice = 695.0,
                            Mileage = 65583,
                            Number = "1291 SR-6",
                            SeatingCapacity = 9,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 7,
                            Brand = "Audi",
                            HirePrice = 684.0,
                            Mileage = 7069,
                            Number = "2554 TL-5",
                            SeatingCapacity = 5,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 8,
                            Brand = "Volvo",
                            HirePrice = 638.0,
                            Mileage = 95063,
                            Number = "9569 TM-2",
                            SeatingCapacity = 8,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 9,
                            Brand = "BMW",
                            HirePrice = 610.0,
                            Mileage = 98671,
                            Number = "2678 WG-6",
                            SeatingCapacity = 8,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 10,
                            Brand = "Volvo",
                            HirePrice = 503.0,
                            Mileage = 68388,
                            Number = "7841 RP-3",
                            SeatingCapacity = 4,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 11,
                            Brand = "BMW",
                            HirePrice = 643.0,
                            Mileage = 94739,
                            Number = "7254 SW-6",
                            SeatingCapacity = 4,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 12,
                            Brand = "Audi",
                            HirePrice = 136.0,
                            Mileage = 19914,
                            Number = "9332 ZK-3",
                            SeatingCapacity = 7,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 13,
                            Brand = "BMW",
                            HirePrice = 947.0,
                            Mileage = 52161,
                            Number = "9900 TU-1",
                            SeatingCapacity = 4,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 14,
                            Brand = "Mercedes",
                            HirePrice = 327.0,
                            Mileage = 93601,
                            Number = "4805 QU-6",
                            SeatingCapacity = 3,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 15,
                            Brand = "Audi",
                            HirePrice = 408.0,
                            Mileage = 37206,
                            Number = "5362 OJ-6",
                            SeatingCapacity = 7,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 16,
                            Brand = "Audi",
                            HirePrice = 186.0,
                            Mileage = 48083,
                            Number = "5038 XA-1",
                            SeatingCapacity = 9,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 17,
                            Brand = "Audi",
                            HirePrice = 210.0,
                            Mileage = 50288,
                            Number = "2717 YZ-6",
                            SeatingCapacity = 9,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 18,
                            Brand = "Audi",
                            HirePrice = 147.0,
                            Mileage = 16525,
                            Number = "2926 ZF-6",
                            SeatingCapacity = 2,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 19,
                            Brand = "BMW",
                            HirePrice = 413.0,
                            Mileage = 86469,
                            Number = "1073 FU-5",
                            SeatingCapacity = 4,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 20,
                            Brand = "BMW",
                            HirePrice = 703.0,
                            Mileage = 28231,
                            Number = "3477 AB-2",
                            SeatingCapacity = 9,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 21,
                            Brand = "Audi",
                            HirePrice = 671.0,
                            Mileage = 37990,
                            Number = "2627 UB-6",
                            SeatingCapacity = 3,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 22,
                            Brand = "Mercedes",
                            HirePrice = 444.0,
                            Mileage = 55491,
                            Number = "8305 AV-4",
                            SeatingCapacity = 5,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 23,
                            Brand = "Mercedes",
                            HirePrice = 235.0,
                            Mileage = 99620,
                            Number = "2101 VL-6",
                            SeatingCapacity = 2,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 24,
                            Brand = "Toyota",
                            HirePrice = 568.0,
                            Mileage = 1056,
                            Number = "9766 MN-4",
                            SeatingCapacity = 9,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 25,
                            Brand = "Volvo",
                            HirePrice = 372.0,
                            Mileage = 359,
                            Number = "4519 JY-3",
                            SeatingCapacity = 3,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 26,
                            Brand = "Audi",
                            HirePrice = 951.0,
                            Mileage = 19461,
                            Number = "2458 FE-2",
                            SeatingCapacity = 9,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 27,
                            Brand = "BMW",
                            HirePrice = 746.0,
                            Mileage = 49875,
                            Number = "9361 ZK-2",
                            SeatingCapacity = 2,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 28,
                            Brand = "Mercedes",
                            HirePrice = 580.0,
                            Mileage = 49196,
                            Number = "2693 ZX-1",
                            SeatingCapacity = 4,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 29,
                            Brand = "Mercedes",
                            HirePrice = 893.0,
                            Mileage = 64353,
                            Number = "3704 WU-1",
                            SeatingCapacity = 3,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 30,
                            Brand = "Audi",
                            HirePrice = 958.0,
                            Mileage = 13831,
                            Number = "2666 XM-2",
                            SeatingCapacity = 9,
                            Status = "Repair"
                        });
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DriverLicenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "44 Cedar Street, Westminster",
                            DriverLicenceNumber = 911066353,
                            Name = "Linda, Lewis",
                            PassportDetails = "FE3005840",
                            PhoneNumber = "+375 29 4996787"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "39 High Street, Bayview",
                            DriverLicenceNumber = 599196788,
                            Name = "James, Clark",
                            PassportDetails = "IR7607639",
                            PhoneNumber = "+375 25 9491008"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "62 Green Avenue, Maplewood",
                            DriverLicenceNumber = 583456215,
                            Name = "Emily, Young",
                            PassportDetails = "VR5052469",
                            PhoneNumber = "+375 33 4872845"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "30 Fifth Street, Mountainview",
                            DriverLicenceNumber = 862770818,
                            Name = "Susan, Walker",
                            PassportDetails = "OJ4934713",
                            PhoneNumber = "+375 25 5207736"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "16 Fourth Street, Villageville",
                            DriverLicenceNumber = 127856558,
                            Name = "James, Hall",
                            PassportDetails = "PG9900460",
                            PhoneNumber = "+375 232 6374803"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "33 Baker Street, Cityville",
                            DriverLicenceNumber = 752474147,
                            Name = "Alice, Martinez",
                            PassportDetails = "OS5133450",
                            PhoneNumber = "+375 29 8816358"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "37 Washington Avenue, Fairview",
                            DriverLicenceNumber = 148897718,
                            Name = "Mary, Wright",
                            PassportDetails = "XK1846059",
                            PhoneNumber = "+375 44 8228807"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "51 Baker Street, Mountainview",
                            DriverLicenceNumber = 105798663,
                            Name = "Robert, Wilson",
                            PassportDetails = "QB5463078",
                            PhoneNumber = "+375 232 7204345"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "4 Main Street, Lakeview",
                            DriverLicenceNumber = 609319106,
                            Name = "Elizabeth, Lewis",
                            PassportDetails = "FQ8216649",
                            PhoneNumber = "+375 33 3010027"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "33 Elm Street, Riverside",
                            DriverLicenceNumber = 512826692,
                            Name = "Anthony, Harris",
                            PassportDetails = "BI9671605",
                            PhoneNumber = "+375 29 7136996"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "66 High Street, Metropolis",
                            DriverLicenceNumber = 292696365,
                            Name = "Patricia, Hall",
                            PassportDetails = "SV6971714",
                            PhoneNumber = "+375 44 7127844"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "59 Pine Street, Villageville",
                            DriverLicenceNumber = 263918006,
                            Name = "Jane, Hall",
                            PassportDetails = "FS1094292",
                            PhoneNumber = "+375 33 7637965"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "83 Fifth Street, Metropolis",
                            DriverLicenceNumber = 138424899,
                            Name = "Matthew, Moore",
                            PassportDetails = "VO2959692",
                            PhoneNumber = "+375 33 4864766"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "12 Second Street, Countyville",
                            DriverLicenceNumber = 828331477,
                            Name = "Daniel, Lewis",
                            PassportDetails = "NV6854389",
                            PhoneNumber = "+375 232 8737495"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "66 High Street, Maplewood",
                            DriverLicenceNumber = 278687645,
                            Name = "Jessica, Harris",
                            PassportDetails = "IH7658021",
                            PhoneNumber = "+375 33 1799369"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "31 Green Avenue, Oakwood",
                            DriverLicenceNumber = 121322673,
                            Name = "Jessica, Anderson",
                            PassportDetails = "BT6449859",
                            PhoneNumber = "+375 44 2949074"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "3 Park Avenue, Hillcrest",
                            DriverLicenceNumber = 397674501,
                            Name = "Mary, Robinson",
                            PassportDetails = "QF4424477",
                            PhoneNumber = "+375 29 6022740"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "70 Central Avenue, Township",
                            DriverLicenceNumber = 858706059,
                            Name = "Robert, Lewis",
                            PassportDetails = "FD7221629",
                            PhoneNumber = "+375 44 7645309"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "13 Pine Street, Valleyview",
                            DriverLicenceNumber = 205207721,
                            Name = "Elizabeth, Smith",
                            PassportDetails = "QI7062390",
                            PhoneNumber = "+375 29 1225857"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "8 First Street, Cityville",
                            DriverLicenceNumber = 438920826,
                            Name = "Charles, Rodriguez",
                            PassportDetails = "CM9641552",
                            PhoneNumber = "+375 232 4643646"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "80 Green Avenue, Evergreen",
                            DriverLicenceNumber = 678809728,
                            Name = "Andrew, Martin",
                            PassportDetails = "RU2114540",
                            PhoneNumber = "+375 29 2803896"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "72 Park Avenue, Cedarville",
                            DriverLicenceNumber = 153653941,
                            Name = "Sarah, Miller",
                            PassportDetails = "RW7388145",
                            PhoneNumber = "+375 33 8387746"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "38 Pine Street, Mountainview",
                            DriverLicenceNumber = 535453549,
                            Name = "Patricia, Jackson",
                            PassportDetails = "LC7353554",
                            PhoneNumber = "+375 25 2451088"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "83 High Street, Villageton",
                            DriverLicenceNumber = 143466410,
                            Name = "Maria, Garcia",
                            PassportDetails = "IN5299436",
                            PhoneNumber = "+375 25 6940560"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "85 Fourth Street, Smalltown",
                            DriverLicenceNumber = 658223022,
                            Name = "Robert, Garcia",
                            PassportDetails = "RC5424479",
                            PhoneNumber = "+375 29 1078092"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "19 Lakeview Drive, Springfield",
                            DriverLicenceNumber = 239435885,
                            Name = "Jennifer, Thomas",
                            PassportDetails = "WH4678299",
                            PhoneNumber = "+375 33 1592437"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "62 School Lane, Riverside",
                            DriverLicenceNumber = 428732781,
                            Name = "James, Young",
                            PassportDetails = "EH6585166",
                            PhoneNumber = "+375 232 4952963"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "82 Washington Avenue, Smalltown",
                            DriverLicenceNumber = 789668484,
                            Name = "Jessica, Anderson",
                            PassportDetails = "BI5500670",
                            PhoneNumber = "+375 33 9940327"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "18 Victory Street, Countyville",
                            DriverLicenceNumber = 810042737,
                            Name = "Mary, Lee",
                            PassportDetails = "YD4756283",
                            PhoneNumber = "+375 232 4334350"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "2 Baker Street, Hillcrest",
                            DriverLicenceNumber = 170098284,
                            Name = "Robert, Taylor",
                            PassportDetails = "WH2417242",
                            PhoneNumber = "+375 25 3945086"
                        });
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Name = "Margaret, Robinson"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Name = "Linda, Brown"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Name = "Thomas, Taylor"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Name = "James, Williams"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Name = "Susan, Thomas"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Name = "Bob, King"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Name = "James, Brown"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Name = "Maria, Garcia"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Name = "Matthew, Wilson"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Name = "Jessica, Moore"
                        });
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("HireHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CarId = 22,
                            CustomerId = 23,
                            Deadline = new DateTime(2023, 10, 15, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 139,
                            OrderDate = new DateTime(2023, 10, 9, 14, 40, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 94548
                        },
                        new
                        {
                            OrderId = 2,
                            CarId = 23,
                            CustomerId = 5,
                            Deadline = new DateTime(2001, 12, 8, 6, 17, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HireHours = 63,
                            OrderDate = new DateTime(2001, 12, 5, 15, 17, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 81802
                        },
                        new
                        {
                            OrderId = 3,
                            CarId = 3,
                            CustomerId = 16,
                            Deadline = new DateTime(2011, 9, 16, 12, 35, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            HireHours = 51,
                            OrderDate = new DateTime(2011, 9, 14, 9, 35, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 25705
                        },
                        new
                        {
                            OrderId = 4,
                            CarId = 16,
                            CustomerId = 19,
                            Deadline = new DateTime(2006, 6, 23, 21, 38, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            HireHours = 42,
                            OrderDate = new DateTime(2006, 6, 22, 3, 38, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 79010
                        },
                        new
                        {
                            OrderId = 5,
                            CarId = 8,
                            CustomerId = 23,
                            Deadline = new DateTime(2000, 11, 19, 22, 37, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HireHours = 19,
                            OrderDate = new DateTime(2000, 11, 19, 3, 37, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 99148
                        },
                        new
                        {
                            OrderId = 6,
                            CarId = 17,
                            CustomerId = 25,
                            Deadline = new DateTime(2017, 9, 6, 17, 8, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HireHours = 156,
                            OrderDate = new DateTime(2017, 8, 31, 5, 8, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 52466
                        },
                        new
                        {
                            OrderId = 7,
                            CarId = 3,
                            CustomerId = 25,
                            Deadline = new DateTime(2021, 7, 19, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            HireHours = 72,
                            OrderDate = new DateTime(2021, 7, 16, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 19262
                        },
                        new
                        {
                            OrderId = 8,
                            CarId = 6,
                            CustomerId = 27,
                            Deadline = new DateTime(2018, 7, 7, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            HireHours = 130,
                            OrderDate = new DateTime(2018, 7, 2, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 82577
                        },
                        new
                        {
                            OrderId = 9,
                            CarId = 25,
                            CustomerId = 9,
                            Deadline = new DateTime(2004, 8, 7, 5, 49, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            HireHours = 110,
                            OrderDate = new DateTime(2004, 8, 2, 15, 49, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 77272
                        },
                        new
                        {
                            OrderId = 10,
                            CarId = 27,
                            CustomerId = 22,
                            Deadline = new DateTime(2001, 4, 16, 9, 58, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 6,
                            OrderDate = new DateTime(2001, 4, 16, 3, 58, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 16309
                        },
                        new
                        {
                            OrderId = 11,
                            CarId = 10,
                            CustomerId = 23,
                            Deadline = new DateTime(2003, 5, 9, 19, 11, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 124,
                            OrderDate = new DateTime(2003, 5, 4, 15, 11, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 73854
                        },
                        new
                        {
                            OrderId = 12,
                            CarId = 21,
                            CustomerId = 29,
                            Deadline = new DateTime(2002, 2, 5, 21, 9, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            HireHours = 126,
                            OrderDate = new DateTime(2002, 1, 31, 15, 9, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 38651
                        },
                        new
                        {
                            OrderId = 13,
                            CarId = 19,
                            CustomerId = 5,
                            Deadline = new DateTime(2019, 6, 23, 22, 4, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            HireHours = 7,
                            OrderDate = new DateTime(2019, 6, 23, 15, 4, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 14542
                        },
                        new
                        {
                            OrderId = 14,
                            CarId = 24,
                            CustomerId = 4,
                            Deadline = new DateTime(2013, 2, 22, 17, 50, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            HireHours = 143,
                            OrderDate = new DateTime(2013, 2, 16, 18, 50, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 78954
                        },
                        new
                        {
                            OrderId = 15,
                            CarId = 12,
                            CustomerId = 16,
                            Deadline = new DateTime(2021, 3, 24, 16, 2, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            HireHours = 109,
                            OrderDate = new DateTime(2021, 3, 20, 3, 2, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 30140
                        },
                        new
                        {
                            OrderId = 16,
                            CarId = 14,
                            CustomerId = 25,
                            Deadline = new DateTime(2017, 8, 12, 4, 40, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            HireHours = 50,
                            OrderDate = new DateTime(2017, 8, 10, 2, 40, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 85667
                        },
                        new
                        {
                            OrderId = 17,
                            CarId = 25,
                            CustomerId = 9,
                            Deadline = new DateTime(2013, 11, 4, 18, 8, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            HireHours = 85,
                            OrderDate = new DateTime(2013, 11, 1, 5, 8, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 88264
                        },
                        new
                        {
                            OrderId = 18,
                            CarId = 16,
                            CustomerId = 14,
                            Deadline = new DateTime(2013, 3, 6, 17, 59, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            HireHours = 8,
                            OrderDate = new DateTime(2013, 3, 6, 9, 59, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 96028
                        },
                        new
                        {
                            OrderId = 19,
                            CarId = 11,
                            CustomerId = 6,
                            Deadline = new DateTime(2014, 10, 19, 3, 58, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            HireHours = 86,
                            OrderDate = new DateTime(2014, 10, 15, 13, 58, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 23210
                        },
                        new
                        {
                            OrderId = 20,
                            CarId = 17,
                            CustomerId = 5,
                            Deadline = new DateTime(2013, 8, 26, 16, 43, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            HireHours = 100,
                            OrderDate = new DateTime(2013, 8, 22, 12, 43, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 24161
                        },
                        new
                        {
                            OrderId = 21,
                            CarId = 3,
                            CustomerId = 18,
                            Deadline = new DateTime(2001, 4, 1, 12, 3, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            HireHours = 45,
                            OrderDate = new DateTime(2001, 3, 30, 15, 3, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 47220
                        },
                        new
                        {
                            OrderId = 22,
                            CarId = 2,
                            CustomerId = 6,
                            Deadline = new DateTime(2018, 12, 26, 11, 31, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            HireHours = 112,
                            OrderDate = new DateTime(2018, 12, 21, 19, 31, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 26784
                        },
                        new
                        {
                            OrderId = 23,
                            CarId = 12,
                            CustomerId = 6,
                            Deadline = new DateTime(2002, 8, 3, 4, 34, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            HireHours = 53,
                            OrderDate = new DateTime(2002, 7, 31, 23, 34, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 61734
                        },
                        new
                        {
                            OrderId = 24,
                            CarId = 8,
                            CustomerId = 4,
                            Deadline = new DateTime(2023, 6, 10, 15, 18, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 101,
                            OrderDate = new DateTime(2023, 6, 6, 10, 18, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 95854
                        },
                        new
                        {
                            OrderId = 25,
                            CarId = 6,
                            CustomerId = 15,
                            Deadline = new DateTime(2004, 4, 27, 13, 58, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            HireHours = 82,
                            OrderDate = new DateTime(2004, 4, 24, 3, 58, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 80848
                        },
                        new
                        {
                            OrderId = 26,
                            CarId = 13,
                            CustomerId = 21,
                            Deadline = new DateTime(2007, 10, 24, 10, 42, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 124,
                            OrderDate = new DateTime(2007, 10, 19, 6, 42, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 12926
                        },
                        new
                        {
                            OrderId = 27,
                            CarId = 21,
                            CustomerId = 21,
                            Deadline = new DateTime(2024, 2, 9, 7, 53, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            HireHours = 66,
                            OrderDate = new DateTime(2024, 2, 6, 13, 53, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 98732
                        },
                        new
                        {
                            OrderId = 28,
                            CarId = 21,
                            CustomerId = 13,
                            Deadline = new DateTime(2019, 6, 16, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            HireHours = 163,
                            OrderDate = new DateTime(2019, 6, 9, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 87549
                        },
                        new
                        {
                            OrderId = 29,
                            CarId = 1,
                            CustomerId = 21,
                            Deadline = new DateTime(2013, 2, 21, 17, 47, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            HireHours = 11,
                            OrderDate = new DateTime(2013, 2, 21, 6, 47, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 70383
                        },
                        new
                        {
                            OrderId = 30,
                            CarId = 23,
                            CustomerId = 15,
                            Deadline = new DateTime(2018, 9, 1, 6, 13, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            HireHours = 4,
                            OrderDate = new DateTime(2018, 9, 1, 2, 13, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 26124
                        },
                        new
                        {
                            OrderId = 31,
                            CarId = 24,
                            CustomerId = 11,
                            Deadline = new DateTime(2012, 9, 4, 12, 17, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            HireHours = 136,
                            OrderDate = new DateTime(2012, 8, 29, 20, 17, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 93175
                        },
                        new
                        {
                            OrderId = 32,
                            CarId = 5,
                            CustomerId = 21,
                            Deadline = new DateTime(2019, 3, 6, 14, 18, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            HireHours = 36,
                            OrderDate = new DateTime(2019, 3, 5, 2, 18, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 47129
                        },
                        new
                        {
                            OrderId = 33,
                            CarId = 4,
                            CustomerId = 23,
                            Deadline = new DateTime(2023, 3, 30, 18, 57, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 52,
                            OrderDate = new DateTime(2023, 3, 28, 14, 57, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 42698
                        },
                        new
                        {
                            OrderId = 34,
                            CarId = 16,
                            CustomerId = 13,
                            Deadline = new DateTime(2013, 9, 26, 5, 51, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            HireHours = 30,
                            OrderDate = new DateTime(2013, 9, 24, 23, 51, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 63479
                        },
                        new
                        {
                            OrderId = 35,
                            CarId = 13,
                            CustomerId = 16,
                            Deadline = new DateTime(2004, 4, 9, 18, 48, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            HireHours = 143,
                            OrderDate = new DateTime(2004, 4, 3, 19, 48, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 38014
                        },
                        new
                        {
                            OrderId = 36,
                            CarId = 13,
                            CustomerId = 6,
                            Deadline = new DateTime(2015, 6, 4, 3, 17, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            HireHours = 29,
                            OrderDate = new DateTime(2015, 6, 2, 22, 17, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 79835
                        },
                        new
                        {
                            OrderId = 37,
                            CarId = 8,
                            CustomerId = 19,
                            Deadline = new DateTime(2018, 1, 7, 23, 23, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 92,
                            OrderDate = new DateTime(2018, 1, 4, 3, 23, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 85011
                        },
                        new
                        {
                            OrderId = 38,
                            CarId = 28,
                            CustomerId = 18,
                            Deadline = new DateTime(2023, 1, 28, 23, 42, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            HireHours = 133,
                            OrderDate = new DateTime(2023, 1, 23, 10, 42, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 82739
                        },
                        new
                        {
                            OrderId = 39,
                            CarId = 26,
                            CustomerId = 7,
                            Deadline = new DateTime(2008, 1, 2, 0, 42, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            HireHours = 41,
                            OrderDate = new DateTime(2007, 12, 31, 7, 42, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 32781
                        },
                        new
                        {
                            OrderId = 40,
                            CarId = 14,
                            CustomerId = 23,
                            Deadline = new DateTime(2002, 9, 10, 15, 49, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 29,
                            OrderDate = new DateTime(2002, 9, 9, 10, 49, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 16079
                        },
                        new
                        {
                            OrderId = 41,
                            CarId = 4,
                            CustomerId = 15,
                            Deadline = new DateTime(2004, 7, 12, 6, 46, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HireHours = 59,
                            OrderDate = new DateTime(2004, 7, 9, 19, 46, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 17020
                        },
                        new
                        {
                            OrderId = 42,
                            CarId = 9,
                            CustomerId = 8,
                            Deadline = new DateTime(2002, 11, 23, 15, 15, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            HireHours = 88,
                            OrderDate = new DateTime(2002, 11, 19, 23, 15, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 51526
                        },
                        new
                        {
                            OrderId = 43,
                            CarId = 16,
                            CustomerId = 21,
                            Deadline = new DateTime(2022, 1, 13, 10, 21, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            HireHours = 67,
                            OrderDate = new DateTime(2022, 1, 10, 15, 21, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 58716
                        },
                        new
                        {
                            OrderId = 44,
                            CarId = 20,
                            CustomerId = 24,
                            Deadline = new DateTime(2015, 5, 13, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            HireHours = 84,
                            OrderDate = new DateTime(2015, 5, 9, 22, 20, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 71255
                        },
                        new
                        {
                            OrderId = 45,
                            CarId = 25,
                            CustomerId = 7,
                            Deadline = new DateTime(2009, 11, 4, 17, 5, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HireHours = 50,
                            OrderDate = new DateTime(2009, 11, 2, 15, 5, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 98318
                        },
                        new
                        {
                            OrderId = 46,
                            CarId = 1,
                            CustomerId = 22,
                            Deadline = new DateTime(2022, 11, 13, 21, 46, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            HireHours = 1,
                            OrderDate = new DateTime(2022, 11, 13, 20, 46, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 97851
                        },
                        new
                        {
                            OrderId = 47,
                            CarId = 12,
                            CustomerId = 10,
                            Deadline = new DateTime(2007, 3, 13, 0, 47, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            HireHours = 164,
                            OrderDate = new DateTime(2007, 3, 6, 4, 47, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 65261
                        },
                        new
                        {
                            OrderId = 48,
                            CarId = 6,
                            CustomerId = 27,
                            Deadline = new DateTime(2009, 11, 15, 23, 28, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            HireHours = 136,
                            OrderDate = new DateTime(2009, 11, 10, 7, 28, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 22342
                        },
                        new
                        {
                            OrderId = 49,
                            CarId = 15,
                            CustomerId = 3,
                            Deadline = new DateTime(2008, 7, 15, 13, 34, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HireHours = 16,
                            OrderDate = new DateTime(2008, 7, 14, 21, 34, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 81257
                        },
                        new
                        {
                            OrderId = 50,
                            CarId = 24,
                            CustomerId = 15,
                            Deadline = new DateTime(2012, 3, 28, 14, 18, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            HireHours = 20,
                            OrderDate = new DateTime(2012, 3, 27, 18, 18, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 34369
                        });
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Order", b =>
                {
                    b.HasOne("Car_hire.DAL.Entities.Models.Car", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_hire.DAL.Entities.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_hire.DAL.Entities.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Car", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Employee", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
