// <auto-generated />
using System;
using Car_hire.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Car_hire.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240313220053_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "brand", new[] { "bmw", "mercedes", "toyota", "volvo", "audi" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status", new[] { "busy", "repair", "available" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("HirePrice")
                        .HasColumnType("double precision");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "BMW",
                            HirePrice = 595.0,
                            Mileage = 44679,
                            Number = "6216 IS-6",
                            SeatingCapacity = 6,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "BMW",
                            HirePrice = 918.0,
                            Mileage = 57996,
                            Number = "4530 DP-5",
                            SeatingCapacity = 6,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "Volvo",
                            HirePrice = 308.0,
                            Mileage = 72369,
                            Number = "1930 FA-4",
                            SeatingCapacity = 3,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 4,
                            Brand = "Mercedes",
                            HirePrice = 526.0,
                            Mileage = 50651,
                            Number = "8504 SG-5",
                            SeatingCapacity = 2,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 5,
                            Brand = "Audi",
                            HirePrice = 629.0,
                            Mileage = 79539,
                            Number = "7259 YR-4",
                            SeatingCapacity = 5,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 6,
                            Brand = "Audi",
                            HirePrice = 538.0,
                            Mileage = 22005,
                            Number = "6173 ZG-2",
                            SeatingCapacity = 4,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 7,
                            Brand = "Audi",
                            HirePrice = 503.0,
                            Mileage = 73253,
                            Number = "9780 GZ-1",
                            SeatingCapacity = 5,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 8,
                            Brand = "Mercedes",
                            HirePrice = 178.0,
                            Mileage = 39563,
                            Number = "1757 PF-4",
                            SeatingCapacity = 2,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 9,
                            Brand = "Mercedes",
                            HirePrice = 872.0,
                            Mileage = 42919,
                            Number = "1085 JJ-2",
                            SeatingCapacity = 3,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 10,
                            Brand = "Audi",
                            HirePrice = 447.0,
                            Mileage = 51686,
                            Number = "3233 BX-2",
                            SeatingCapacity = 3,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 11,
                            Brand = "Mercedes",
                            HirePrice = 513.0,
                            Mileage = 35069,
                            Number = "8102 EI-2",
                            SeatingCapacity = 2,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 12,
                            Brand = "BMW",
                            HirePrice = 188.0,
                            Mileage = 84195,
                            Number = "5657 ZH-3",
                            SeatingCapacity = 4,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 13,
                            Brand = "Mercedes",
                            HirePrice = 920.0,
                            Mileage = 55916,
                            Number = "7107 WA-3",
                            SeatingCapacity = 8,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 14,
                            Brand = "Audi",
                            HirePrice = 117.0,
                            Mileage = 82842,
                            Number = "9156 RI-6",
                            SeatingCapacity = 7,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 15,
                            Brand = "Audi",
                            HirePrice = 146.0,
                            Mileage = 92487,
                            Number = "3723 DT-3",
                            SeatingCapacity = 4,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 16,
                            Brand = "Toyota",
                            HirePrice = 989.0,
                            Mileage = 13286,
                            Number = "7606 DR-6",
                            SeatingCapacity = 7,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 17,
                            Brand = "Mercedes",
                            HirePrice = 492.0,
                            Mileage = 78622,
                            Number = "7912 QL-1",
                            SeatingCapacity = 3,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 18,
                            Brand = "Volvo",
                            HirePrice = 555.0,
                            Mileage = 86270,
                            Number = "4698 VJ-6",
                            SeatingCapacity = 8,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 19,
                            Brand = "BMW",
                            HirePrice = 373.0,
                            Mileage = 11357,
                            Number = "6029 ZY-6",
                            SeatingCapacity = 3,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 20,
                            Brand = "Audi",
                            HirePrice = 811.0,
                            Mileage = 31207,
                            Number = "6144 WY-5",
                            SeatingCapacity = 5,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 21,
                            Brand = "Volvo",
                            HirePrice = 571.0,
                            Mileage = 45096,
                            Number = "8070 VY-6",
                            SeatingCapacity = 6,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 22,
                            Brand = "BMW",
                            HirePrice = 179.0,
                            Mileage = 67446,
                            Number = "7623 ZO-1",
                            SeatingCapacity = 4,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 23,
                            Brand = "Toyota",
                            HirePrice = 460.0,
                            Mileage = 98829,
                            Number = "2679 IW-4",
                            SeatingCapacity = 8,
                            Status = "Available"
                        },
                        new
                        {
                            CarId = 24,
                            Brand = "Toyota",
                            HirePrice = 892.0,
                            Mileage = 7126,
                            Number = "5007 SN-5",
                            SeatingCapacity = 4,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 25,
                            Brand = "BMW",
                            HirePrice = 202.0,
                            Mileage = 48416,
                            Number = "5542 BY-6",
                            SeatingCapacity = 6,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 26,
                            Brand = "Volvo",
                            HirePrice = 111.0,
                            Mileage = 66525,
                            Number = "6762 AK-4",
                            SeatingCapacity = 4,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 27,
                            Brand = "Toyota",
                            HirePrice = 256.0,
                            Mileage = 75541,
                            Number = "4831 SO-5",
                            SeatingCapacity = 5,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 28,
                            Brand = "Toyota",
                            HirePrice = 805.0,
                            Mileage = 4884,
                            Number = "3451 IQ-4",
                            SeatingCapacity = 8,
                            Status = "Repair"
                        },
                        new
                        {
                            CarId = 29,
                            Brand = "Toyota",
                            HirePrice = 618.0,
                            Mileage = 71078,
                            Number = "6896 FX-3",
                            SeatingCapacity = 7,
                            Status = "Busy"
                        },
                        new
                        {
                            CarId = 30,
                            Brand = "Volvo",
                            HirePrice = 997.0,
                            Mileage = 33043,
                            Number = "9630 PU-5",
                            SeatingCapacity = 6,
                            Status = "Repair"
                        });
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "97 Ninth Street, Lakeview",
                            Name = "John Brown",
                            PassportDetails = "HH6177350",
                            PhoneNumber = "+375 29 7229503"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "50 Lakeview Drive, Lexington",
                            Name = "Matthew Clark",
                            PassportDetails = "UK5930116",
                            PhoneNumber = "+375 33 7084024"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "97 Eighth Street, Townville",
                            Name = "Linda Miller",
                            PassportDetails = "KK7039373",
                            PhoneNumber = "+375 33 4646062"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "92 Eighth Street, Springfield",
                            Name = "Margaret Walker",
                            PassportDetails = "AQ5318582",
                            PhoneNumber = "+375 25 1272502"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "68 River Road, Northfield",
                            Name = "Charles Jackson",
                            PassportDetails = "ZS7662736",
                            PhoneNumber = "+375 44 5294252"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "94 Central Avenue, Township",
                            Name = "Matthew Hall",
                            PassportDetails = "QW8158281",
                            PhoneNumber = "+375 44 7937687"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "10 Elm Street, Eastwood",
                            Name = "Barbara Lee",
                            PassportDetails = "YS3278643",
                            PhoneNumber = "+375 29 8747964"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "93 Tenth Street, Springfield",
                            Name = "Maria Allen",
                            PassportDetails = "EB6781365",
                            PhoneNumber = "+375 44 3087871"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "59 Washington Avenue, Suburbia",
                            Name = "Linda Miller",
                            PassportDetails = "TI8413589",
                            PhoneNumber = "+375 25 5076646"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "36 Tenth Street, Springfield",
                            Name = "Elizabeth Thompson",
                            PassportDetails = "QI7420873",
                            PhoneNumber = "+375 29 1946349"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "23 Washington Avenue, Oakwood",
                            Name = "Jessica Miller",
                            PassportDetails = "GH2632456",
                            PhoneNumber = "+375 33 7215455"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "25 School Lane, Fairview",
                            Name = "Margaret Walker",
                            PassportDetails = "SV4595641",
                            PhoneNumber = "+375 25 8264964"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "21 Baker Street, Evergreen",
                            Name = "Robert Anderson",
                            PassportDetails = "JH8905517",
                            PhoneNumber = "+375 33 7138300"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "5 Sunset Boulevard, Villageville",
                            Name = "Sarah Smith",
                            PassportDetails = "OR4982548",
                            PhoneNumber = "+375 33 1684760"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "34 Central Avenue, Southfield",
                            Name = "Charles Thomas",
                            PassportDetails = "RF1521280",
                            PhoneNumber = "+375 44 5437571"
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "14 River Road, Valleyview",
                            Name = "Susan Young",
                            PassportDetails = "UV2449492",
                            PhoneNumber = "+375 232 7385583"
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "56 Maple Street, Suburbia",
                            Name = "Andrew Anderson",
                            PassportDetails = "HK7244740",
                            PhoneNumber = "+375 232 7002906"
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "21 Fifth Street, Lexington",
                            Name = "Andrew Allen",
                            PassportDetails = "WI2566590",
                            PhoneNumber = "+375 33 2410536"
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "99 Cedar Street, Harbor City",
                            Name = "Anthony Davis",
                            PassportDetails = "SB6107658",
                            PhoneNumber = "+375 44 3643747"
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "76 Sixth Street, Harbor City",
                            Name = "Maria Young",
                            PassportDetails = "FM5409031",
                            PhoneNumber = "+375 25 4350149"
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "73 Oak Street, Eastwood",
                            Name = "Maria Wilson",
                            PassportDetails = "NI1726114",
                            PhoneNumber = "+375 44 8625681"
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "43 Fifth Street, Fairview",
                            Name = "Thomas Harris",
                            PassportDetails = "BB2680773",
                            PhoneNumber = "+375 29 8934872"
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "62 Broadway, Maplewood",
                            Name = "Elizabeth Miller",
                            PassportDetails = "DJ1290611",
                            PhoneNumber = "+375 33 1640028"
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "89 Sunset Boulevard, Mountainview",
                            Name = "John Lewis",
                            PassportDetails = "IU1969560",
                            PhoneNumber = "+375 29 5362412"
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "14 First Street, Townville",
                            Name = "Margaret Wilson",
                            PassportDetails = "VX6584632",
                            PhoneNumber = "+375 44 9540160"
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "29 School Lane, Harbor City",
                            Name = "Patricia White",
                            PassportDetails = "NT7748872",
                            PhoneNumber = "+375 44 8303963"
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "52 River Road, Hillcrest",
                            Name = "William Taylor",
                            PassportDetails = "GC6456631",
                            PhoneNumber = "+375 232 6630318"
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "45 Oak Street, Valleyview",
                            Name = "William Allen",
                            PassportDetails = "WL6816454",
                            PhoneNumber = "+375 232 6756375"
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "4 Sixth Street, Northfield",
                            Name = "Michael White",
                            PassportDetails = "LF9444229",
                            PhoneNumber = "+375 44 1083752"
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "22 Second Street, Cedarville",
                            Name = "James Allen",
                            PassportDetails = "QG4134025",
                            PhoneNumber = "+375 33 3282386"
                        });
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp");

                    b.Property<int>("HireHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CarId = 13,
                            CustomerId = 19,
                            Deadline = new DateTime(2014, 10, 28, 3, 15, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 19,
                            OrderDate = new DateTime(2014, 10, 27, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 70356
                        },
                        new
                        {
                            OrderId = 2,
                            CarId = 26,
                            CustomerId = 29,
                            Deadline = new DateTime(2018, 4, 23, 19, 1, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 44,
                            OrderDate = new DateTime(2018, 4, 21, 23, 1, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 16887
                        },
                        new
                        {
                            OrderId = 3,
                            CarId = 1,
                            CustomerId = 2,
                            Deadline = new DateTime(2021, 5, 31, 17, 6, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 126,
                            OrderDate = new DateTime(2021, 5, 26, 11, 6, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 27430
                        },
                        new
                        {
                            OrderId = 4,
                            CarId = 13,
                            CustomerId = 7,
                            Deadline = new DateTime(2011, 12, 6, 18, 21, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 59,
                            OrderDate = new DateTime(2011, 12, 4, 7, 21, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 50601
                        },
                        new
                        {
                            OrderId = 5,
                            CarId = 10,
                            CustomerId = 3,
                            Deadline = new DateTime(2023, 5, 30, 20, 11, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 153,
                            OrderDate = new DateTime(2023, 5, 24, 11, 11, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 48006
                        },
                        new
                        {
                            OrderId = 6,
                            CarId = 11,
                            CustomerId = 15,
                            Deadline = new DateTime(2018, 10, 7, 15, 44, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 44,
                            OrderDate = new DateTime(2018, 10, 5, 19, 44, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 57287
                        },
                        new
                        {
                            OrderId = 7,
                            CarId = 13,
                            CustomerId = 5,
                            Deadline = new DateTime(2024, 2, 2, 11, 7, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 166,
                            OrderDate = new DateTime(2024, 1, 26, 13, 7, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 30214
                        },
                        new
                        {
                            OrderId = 8,
                            CarId = 22,
                            CustomerId = 27,
                            Deadline = new DateTime(2021, 1, 22, 4, 47, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 107,
                            OrderDate = new DateTime(2021, 1, 17, 17, 47, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 94030
                        },
                        new
                        {
                            OrderId = 9,
                            CarId = 10,
                            CustomerId = 11,
                            Deadline = new DateTime(2018, 7, 11, 5, 51, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 160,
                            OrderDate = new DateTime(2018, 7, 4, 13, 51, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 16360
                        },
                        new
                        {
                            OrderId = 10,
                            CarId = 15,
                            CustomerId = 29,
                            Deadline = new DateTime(2004, 12, 20, 21, 27, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 27,
                            OrderDate = new DateTime(2004, 12, 19, 18, 27, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 50077
                        },
                        new
                        {
                            OrderId = 11,
                            CarId = 7,
                            CustomerId = 12,
                            Deadline = new DateTime(2009, 5, 7, 18, 57, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 82,
                            OrderDate = new DateTime(2009, 5, 4, 8, 57, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 11626
                        },
                        new
                        {
                            OrderId = 12,
                            CarId = 10,
                            CustomerId = 12,
                            Deadline = new DateTime(2023, 11, 30, 15, 47, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 150,
                            OrderDate = new DateTime(2023, 11, 24, 9, 47, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 84623
                        },
                        new
                        {
                            OrderId = 13,
                            CarId = 23,
                            CustomerId = 22,
                            Deadline = new DateTime(2006, 12, 15, 7, 6, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 36,
                            OrderDate = new DateTime(2006, 12, 13, 19, 6, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 50985
                        },
                        new
                        {
                            OrderId = 14,
                            CarId = 18,
                            CustomerId = 17,
                            Deadline = new DateTime(2015, 10, 28, 17, 39, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 69,
                            OrderDate = new DateTime(2015, 10, 25, 20, 39, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 80068
                        },
                        new
                        {
                            OrderId = 15,
                            CarId = 6,
                            CustomerId = 23,
                            Deadline = new DateTime(2003, 10, 24, 0, 20, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 79,
                            OrderDate = new DateTime(2003, 10, 20, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 40381
                        },
                        new
                        {
                            OrderId = 16,
                            CarId = 15,
                            CustomerId = 21,
                            Deadline = new DateTime(2019, 10, 7, 1, 11, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 135,
                            OrderDate = new DateTime(2019, 10, 1, 10, 11, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 92551
                        },
                        new
                        {
                            OrderId = 17,
                            CarId = 12,
                            CustomerId = 8,
                            Deadline = new DateTime(2002, 1, 9, 9, 17, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 66,
                            OrderDate = new DateTime(2002, 1, 6, 15, 17, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 10458
                        },
                        new
                        {
                            OrderId = 18,
                            CarId = 23,
                            CustomerId = 18,
                            Deadline = new DateTime(2004, 2, 4, 13, 47, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 164,
                            OrderDate = new DateTime(2004, 1, 28, 17, 47, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 88809
                        },
                        new
                        {
                            OrderId = 19,
                            CarId = 26,
                            CustomerId = 6,
                            Deadline = new DateTime(2016, 11, 17, 21, 46, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 135,
                            OrderDate = new DateTime(2016, 11, 12, 6, 46, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 43963
                        },
                        new
                        {
                            OrderId = 20,
                            CarId = 12,
                            CustomerId = 13,
                            Deadline = new DateTime(2018, 6, 7, 7, 32, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 119,
                            OrderDate = new DateTime(2018, 6, 2, 8, 32, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 89578
                        },
                        new
                        {
                            OrderId = 21,
                            CarId = 27,
                            CustomerId = 18,
                            Deadline = new DateTime(2020, 5, 6, 10, 4, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 46,
                            OrderDate = new DateTime(2020, 5, 4, 12, 4, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 95219
                        },
                        new
                        {
                            OrderId = 22,
                            CarId = 29,
                            CustomerId = 14,
                            Deadline = new DateTime(2015, 11, 27, 8, 59, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 36,
                            OrderDate = new DateTime(2015, 11, 25, 20, 59, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 43114
                        },
                        new
                        {
                            OrderId = 23,
                            CarId = 1,
                            CustomerId = 7,
                            Deadline = new DateTime(2010, 4, 8, 21, 54, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 51,
                            OrderDate = new DateTime(2010, 4, 6, 18, 54, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 93173
                        },
                        new
                        {
                            OrderId = 24,
                            CarId = 20,
                            CustomerId = 18,
                            Deadline = new DateTime(2002, 10, 21, 11, 13, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 111,
                            OrderDate = new DateTime(2002, 10, 16, 20, 13, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 16009
                        },
                        new
                        {
                            OrderId = 25,
                            CarId = 29,
                            CustomerId = 13,
                            Deadline = new DateTime(2016, 3, 4, 16, 59, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 19,
                            OrderDate = new DateTime(2016, 3, 3, 21, 59, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 67188
                        },
                        new
                        {
                            OrderId = 26,
                            CarId = 7,
                            CustomerId = 13,
                            Deadline = new DateTime(2021, 12, 10, 4, 27, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 110,
                            OrderDate = new DateTime(2021, 12, 5, 14, 27, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 37464
                        },
                        new
                        {
                            OrderId = 27,
                            CarId = 21,
                            CustomerId = 24,
                            Deadline = new DateTime(2013, 11, 29, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 116,
                            OrderDate = new DateTime(2013, 11, 24, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 66590
                        },
                        new
                        {
                            OrderId = 28,
                            CarId = 17,
                            CustomerId = 25,
                            Deadline = new DateTime(2018, 12, 20, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 166,
                            OrderDate = new DateTime(2018, 12, 13, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 21789
                        },
                        new
                        {
                            OrderId = 29,
                            CarId = 11,
                            CustomerId = 19,
                            Deadline = new DateTime(2000, 11, 10, 9, 23, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 77,
                            OrderDate = new DateTime(2000, 11, 7, 4, 23, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 96391
                        },
                        new
                        {
                            OrderId = 30,
                            CarId = 8,
                            CustomerId = 23,
                            Deadline = new DateTime(2013, 1, 10, 7, 1, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 102,
                            OrderDate = new DateTime(2013, 1, 6, 1, 1, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 23958
                        },
                        new
                        {
                            OrderId = 31,
                            CarId = 23,
                            CustomerId = 6,
                            Deadline = new DateTime(2020, 4, 18, 1, 33, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 117,
                            OrderDate = new DateTime(2020, 4, 13, 4, 33, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 95730
                        },
                        new
                        {
                            OrderId = 32,
                            CarId = 10,
                            CustomerId = 5,
                            Deadline = new DateTime(2007, 1, 23, 14, 1, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 47,
                            OrderDate = new DateTime(2007, 1, 21, 15, 1, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 99447
                        },
                        new
                        {
                            OrderId = 33,
                            CarId = 7,
                            CustomerId = 8,
                            Deadline = new DateTime(2000, 3, 15, 0, 41, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 8,
                            OrderDate = new DateTime(2000, 3, 14, 16, 41, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 88797
                        },
                        new
                        {
                            OrderId = 34,
                            CarId = 28,
                            CustomerId = 2,
                            Deadline = new DateTime(2007, 11, 22, 13, 2, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 107,
                            OrderDate = new DateTime(2007, 11, 18, 2, 2, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 58206
                        },
                        new
                        {
                            OrderId = 35,
                            CarId = 3,
                            CustomerId = 17,
                            Deadline = new DateTime(2021, 9, 14, 3, 33, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 71,
                            OrderDate = new DateTime(2021, 9, 11, 4, 33, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 88203
                        },
                        new
                        {
                            OrderId = 36,
                            CarId = 22,
                            CustomerId = 29,
                            Deadline = new DateTime(2000, 8, 12, 13, 34, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 97,
                            OrderDate = new DateTime(2000, 8, 8, 12, 34, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 61339
                        },
                        new
                        {
                            OrderId = 37,
                            CarId = 3,
                            CustomerId = 21,
                            Deadline = new DateTime(2000, 2, 2, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 36,
                            OrderDate = new DateTime(2000, 2, 1, 1, 10, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 91599
                        },
                        new
                        {
                            OrderId = 38,
                            CarId = 26,
                            CustomerId = 21,
                            Deadline = new DateTime(2009, 3, 5, 9, 55, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 24,
                            OrderDate = new DateTime(2009, 3, 4, 9, 55, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 29867
                        },
                        new
                        {
                            OrderId = 39,
                            CarId = 29,
                            CustomerId = 21,
                            Deadline = new DateTime(2010, 1, 12, 1, 29, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 80,
                            OrderDate = new DateTime(2010, 1, 8, 17, 29, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 65483
                        },
                        new
                        {
                            OrderId = 40,
                            CarId = 20,
                            CustomerId = 27,
                            Deadline = new DateTime(2002, 8, 17, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 89,
                            OrderDate = new DateTime(2002, 8, 13, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 18795
                        },
                        new
                        {
                            OrderId = 41,
                            CarId = 18,
                            CustomerId = 21,
                            Deadline = new DateTime(2016, 8, 30, 2, 27, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 111,
                            OrderDate = new DateTime(2016, 8, 25, 11, 27, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 84945
                        },
                        new
                        {
                            OrderId = 42,
                            CarId = 15,
                            CustomerId = 6,
                            Deadline = new DateTime(2000, 11, 2, 8, 9, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 108,
                            OrderDate = new DateTime(2000, 10, 28, 20, 9, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 34330
                        },
                        new
                        {
                            OrderId = 43,
                            CarId = 8,
                            CustomerId = 18,
                            Deadline = new DateTime(2002, 4, 4, 5, 27, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 146,
                            OrderDate = new DateTime(2002, 3, 29, 3, 27, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 22364
                        },
                        new
                        {
                            OrderId = 44,
                            CarId = 23,
                            CustomerId = 14,
                            Deadline = new DateTime(2012, 12, 10, 10, 46, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 40,
                            OrderDate = new DateTime(2012, 12, 8, 18, 46, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 67912
                        },
                        new
                        {
                            OrderId = 45,
                            CarId = 3,
                            CustomerId = 21,
                            Deadline = new DateTime(2023, 2, 26, 19, 28, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 158,
                            OrderDate = new DateTime(2023, 2, 20, 5, 28, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 27058
                        },
                        new
                        {
                            OrderId = 46,
                            CarId = 1,
                            CustomerId = 4,
                            Deadline = new DateTime(2009, 4, 9, 4, 39, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 147,
                            OrderDate = new DateTime(2009, 4, 3, 1, 39, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 46690
                        },
                        new
                        {
                            OrderId = 47,
                            CarId = 29,
                            CustomerId = 23,
                            Deadline = new DateTime(2019, 9, 26, 4, 6, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 37,
                            OrderDate = new DateTime(2019, 9, 24, 15, 6, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 26816
                        },
                        new
                        {
                            OrderId = 48,
                            CarId = 3,
                            CustomerId = 11,
                            Deadline = new DateTime(2004, 3, 6, 0, 20, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 143,
                            OrderDate = new DateTime(2004, 2, 29, 1, 20, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 30978
                        },
                        new
                        {
                            OrderId = 49,
                            CarId = 2,
                            CustomerId = 27,
                            Deadline = new DateTime(2023, 6, 15, 21, 44, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 13,
                            OrderDate = new DateTime(2023, 6, 15, 8, 44, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 51436
                        },
                        new
                        {
                            OrderId = 50,
                            CarId = 9,
                            CustomerId = 4,
                            Deadline = new DateTime(2009, 12, 15, 20, 27, 0, 0, DateTimeKind.Unspecified),
                            HireHours = 69,
                            OrderDate = new DateTime(2009, 12, 12, 23, 27, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = 93624
                        });
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Order", b =>
                {
                    b.HasOne("Car_hire.DAL.Entities.Models.Car", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_hire.DAL.Entities.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Car", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Car_hire.DAL.Entities.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
